version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.localdev
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.localdev
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'
    env_file:
    - .env

  nginx:
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
      - frontend

volumes:
  mysql_data: